"""remove video_id

Revision ID: d9d347b2fb46
Revises: ec20d7445b54
Create Date: 2026-03-16 12:23:18.578943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d347b2fb46'
down_revision: Union[str, Sequence[str], None] = 'ec20d7445b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'video_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('video_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
