"""add video_url to course

Revision ID: ec20d7445b54
Revises: 5f3e10b8d176
Create Date: 2026-03-16 11:40:09.520930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec20d7445b54'
down_revision: Union[str, Sequence[str], None] = '5f3e10b8d176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('course_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'course_url')
    # ### end Alembic commands ###
